import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 0,
    backgroundColor: "#C1DFE2",
    // paddingTop: 50,
    // paddingBottom: 16,
    // paddingLeft: 16,
    // paddingRight: 16,
  },
  temp: {
    position: "absolute",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    top: 0,
    left: 0,
    width: "100%",
    backgroundColor: "lightgreen",
  },

  mainContainer: {
    flex: 4,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    paddingTop: 10,
    // paddingBottom: 16,
    // paddingLeft: 16,
    // paddingRight: 16,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    backgroundColor: "#2C333F",
  },
  header: {
    flex: 0,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    // backgroundColor: "red",
  },
  closeBtnBox: {},
  closeBtn: {
    padding: 16,
    // marginBottom: 33,
    // width: "100%",
    fontSize: 24,
    color: "#fff",
  },
  torchBox: {},
  torchIcon: {
    padding: 16,
  },
  title: {
    marginBottom: 33,
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
  },
  // cameraContainer
  cameraContainer: {
    flex: 0,
    alignItems: "center",
    justifyContent: "center",
    width: "95%",
    height: 300,
    borderRadius: 32,
    overflow: "hidden",
    // backgroundColor: "red",
  },
  cameraBorderContainer: {
    flex: 0,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  cameraBorderBox: {
    width: 250,
    height: 250,
    // borderWidth: 10,
    // borderColor: "blue",
    // borderRadius: 50,
  },
  cameraBorderTopLeft: {
    position: "absolute",
    width: 55,
    height: 55,
    left: 0,
    top: 0,
    borderTopStartRadius: 40,
    borderTopWidth: 8,
    borderLeftWidth: 8,
    borderColor: "#E3E3E3",
  },
  cameraBorderTopRight: {
    position: "absolute",
    width: 55,
    height: 55,
    right: 0,
    top: 0,
    borderTopEndRadius: 40,
    borderTopWidth: 8,
    borderRightWidth: 8,
    borderColor: "#E3E3E3",
  },
  cameraBorderBottomLeft: {
    position: "absolute",
    width: 55,
    height: 55,
    left: 0,
    bottom: 0,
    borderBottomStartRadius: 40,
    borderBottomWidth: 8,
    borderLeftWidth: 8,
    borderColor: "#E3E3E3",
  },
  cameraBorderBottomRight: {
    position: "absolute",
    width: 55,
    height: 55,
    right: 0,
    bottom: 0,
    borderBottomEndRadius: 40,
    borderBottomWidth: 8,
    borderRightWidth: 8,
    borderColor: "#E3E3E3",
  },
  actionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingLeft: 16,
    paddingRight: 16,
  },
  toggleInputStyle: {
    width: "100%",
    paddingTop: 19,
    paddingBottom: 19,
    backgroundColor: "#FFC200",
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  toggleInputStyleText: {
    color: "#2C333F",
    fontSize: 15,
    fontWeight: "bold",
  },
  // inputFormContainer
  inputFormContainer: {
    flex: 0,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
    // backgroundColor: "lightgreen",
    paddingLeft: 16,
    paddingRight: 16,
  },
  label: {
    marginBottom: 0, // 調整標籤和輸入框之間的間距
    fontSize: 12,
    color: "#FFF",
  },
  input: {
    width: "100%",
    height: 40,
    // borderColor: "transparent",
    borderBottomWidth: 1,
    borderBottomColor: "#FFF",
    // paddingHorizontal: 10,
    fontSize: 20,
    fontWeight: "600",
    color: "#FFF",
  },
  inputError: {
    borderColor: "red", // 驗證錯誤時顯示紅色邊框
  },
  userInputVinContainer: {
    width: "100%",
    marginTop: 32,
    paddingTop: 19,
    paddingBottom: 19,
    borderColor: "#FFC200",
    borderWidth: 1,
    borderRadius: 40,
  },
  submitUserInputVinBtn: {
    width: "100%",
  },
  submitUserInputVinBtnText: {
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    color: "#FFC200",
  },
});

export default styles;
