import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 0,
    backgroundColor: '#C1DFE2',
    paddingTop: 50,
    // paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  // topHeader
  topHeaderContainer: {
    flex: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    // backgroundColor: "lightblue",
    // marginBottom: 60,
  },
  topHeaderActionBox: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    // backgroundColor: "lightgreen",
    paddingTop: 16,
    paddingBottom: 16,
    // padding: 16,
  },
  topHeaderText: {
    // padding: 16,
    fontSize: 10,
    marginBottom: 2,
  },
  topHeaderActionBtn: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    backgroundColor: '#FFF',
  },
  todayBtn: {
    width: 60,
    borderRadius: 4,
    backgroundColor: '#FFC200', // 黃色
  },
  customBtn: {
    width: 60,
    borderRadius: 4,
    backgroundColor: '#0096A3',
  },
  topHeaderActionBtnText: {
    fontSize: 14,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 20,
  },
  // bodyContainer
  bodyContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    // backgroundColor: "lightgray",
  },
  // topArea
  topArea: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    gap: 12,
    // backgroundColor: "lightgray",
  },
  logoTypographyImageBox: {},
  logoTypographyImage: {
    width: 183,
    height: 30,
    resizeMode: 'cover',
  },
  kiaLogoImage: {
    height: 20,
    resizeMode: 'cover',
  },
  middleX: {
    fontSize: 18,
    fontWeight: '600',
  },
  accountBox: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // width: 90,
    // height: 90,
    // backgroundColor: '#FFF',
    // borderRadius: 50,
  },
  accountBoxText: {
    fontSize: 28,
    fontWeight: '600',
  },
  // listContainer
  listContainer: {
    flex: 1,
    marginTop: 48,
    width: '100%',
    // backgroundColor: "yellow",
  },
  listHeadLineArea: {
    flex: 0,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  listHeadLineTitles: {},
  listHeadLineTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  listHeadLineSubtitleBox: {
    flex: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  listHeadLineSubtitle: {
    fontSize: 12,
    lineHeight: 25,
  },
  evccidCountBox: {
    flex: 0,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 0,
  },
  evccidCountText: {
    fontSize: 12,
    lineHeight: 25,
  },
  evccidCountTextNumber: {
    fontSize: 14,
    lineHeight: 25,
    backgroundColor: '#0096A3',
    paddingHorizontal: 6,
    borderRadius: 4,
    fontWeight: '800',
    color: '#FFF',
  },
  evccidCountDescriptionText: {
    fontSize: 10,
    lineHeight: 25,
  },
  downloadBtn: {
    paddingHorizontal: 16,
    paddingVertical: 4,
    paddingBottom: 6,
    borderWidth: 1,
    borderColor: '#2C333F',
    borderRadius: 50,
  },
  downloadBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2C333F',
  },
  list: {
    flex: 1,
    // marginTop: 48,
    width: '100%',
  },
  listIsEmpty: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '10%',
    // position: "absolute",
    // top: 0,
    // bottom: 0,
    // left: 0,
    // right: 0,
    // backgroundColor: "green",
  },
  testBtnArea: {
    position: 'absolute',
    bottom: 100,
    left: 50,
    right: 50,
  },
  createActionArea: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 8,
    // paddingBottom 現在由動態計算決定（在組件中設定）
    // width: "100%",
    // backgroundColor: "red",
    pointerEvents: 'box-none',
  },
  userActionArea: {
    flex: 0,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    position: 'absolute',
    bottom: 0,
    right: 16,
    paddingTop: 8,
    // paddingBottom 現在由動態計算決定（在組件中設定）
    // width: "100%",
    // backgroundColor: "red",
    pointerEvents: 'box-none',
  },
  createActionBtnBox: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  createBtnAreaPlusIconBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 85,
    height: 85,
    fontSize: 36,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: '#C1DFE2',
  },
  createBtnAreaPlusText: {
    fontSize: 12,
    fontWeight: '800',
  },
  userActionBtnAreaPlusIconBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    height: 60,
    fontSize: 24,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: '#C1DFE2',
  },
  userActionBtnText: {
    fontSize: 10,
    fontWeight: '300',
  },
  bgYellow: {
    backgroundColor: '#FFC200',
  },
  bgGray: {
    backgroundColor: '#9a9a9a',
  },
  bgPrimary: {
    backgroundColor: '#0096A3',
  },
  // createBtnAreaPlusIcon: {
  //   transform: [{ rotate: "45deg" }],
  //   fontSize: 20,
  //   fontWeight: "800",
  // },
});

export default styles;
