import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    backgroundColor: '#2C333F',
    // paddingTop: 50,
    // paddingBottom: 16,
    // paddingLeft: 16,
    // paddingRight: 16,
  },
  mainContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 300,
    // paddingTop: 50,
    // paddingBottom: 16,
    // paddingLeft: 16,
    // paddingRight: 16,
    // backgroundColor: "gray",
  },
  title: {
    marginBottom: 33,
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
  },
  confirmInfoContainer: {
    flex: 0,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    // backgroundColor: "lightgreen",
    paddingLeft: 16,
    paddingRight: 16,
  },
  confirmInfos: {
    width: '100%',
    borderTopWidth: 2,
    borderColor: '#FFF',
    // backgroundColor: "red",
  },
  confirmInfoBox: {
    flex: 0,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 24,
    borderBottomWidth: 2,
    borderColor: '#FFF',
    // backgroundColor: "gray",
  },
  confirmInfoTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#FFF',
  },
  infoTitle: {
    marginBottom: 12, // 調整標籤和輸入框之間的間距
    fontSize: 12,
    color: '#FFF',
  },
  infoText: {
    width: '100%',
    height: 40,
    // borderColor: "transparent",
    // paddingHorizontal: 10,
    letterSpacing: 3,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
    color: '#FFF',
  },
  submitBtnContainer: {
    width: '100%',
    marginTop: 32,
    borderColor: '#FFC200',
    borderWidth: 1,
    borderRadius: 40,
  },
  submitUserInputVinBtn: {
    width: '100%',
  },
  submitUserInputVinBtnText: {
    paddingTop: 19,
    paddingBottom: 19,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    color: '#FFC200',
    borderRadius: 40,
  },
  cancleBtnContainer: {
    width: '100%',
    marginTop: 32,
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // paddingTop: 19,
    // paddingBottom: 19,
    // borderColor: "#FFC200",
    // borderWidth: 1,
    // borderRadius: 40,
  },
  cancleBtn: {
    // backgroundColor: "red",
  },
  cancleBtnText: {
    color: '#fff',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContent: {
    width: '80%',
    height: 350,
    backgroundColor: '#2C333F',
    borderRadius: 10,
    padding: 20,
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageContainer: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepTextContainer: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 50,
    marginBottom: 5,
    borderRadius: 30,
    backgroundColor: '#FFC200',
    fontSize: 24,
    fontWeight: '800',
  },
  messageText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFC200',
  },
  subMessageText: {
    marginTop: 10,
    marginBottom: 20,
    fontSize: 14,
    fontWeight: '400',
    color: '#aaa',
  },
  confirmButton: {
    width: '100%',
    marginTop: 15,
    borderColor: '#FFC200',
    borderWidth: 1,
    borderRadius: 40,
  },
  backHomeBtn: {
    marginTop: 30,
    borderColor: '#aaa',
  },
  confirmButtonText: {
    paddingTop: 19,
    paddingBottom: 19,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    color: '#FFC200',
    borderRadius: 40,
  },
  backHomeBtnText: {
    color: '#aaa',
  },
});

export default styles;
